version: '3'

services: 
  users-mysql:
    image: mysql
    restart: always
    container_name: users-mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3307
    ports:
      - 3307:3307
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes: 
      - ./init.sql

  users-node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: node-mysql-app
    container_name: users-node
    env_file: .env
    ports: 
      - 8000:3000
    volumes:
      - .:/app
    command: bash -c 'while !</dev/tcp/users-mysql/3306; do sleep 1; done; npm run dev'
    depends_on:
      users-mysql:
        condition: service_healthy

volumes: 
  db-config:
  db-data: